package com.bot.telegram.app.core.enums;

public enum FluxoLancDespesas {


    INFORMAR_CATAO,
    INFORMAR_CATEGORIA,
    INFORMAR_VALOR_DESCRICAO_PARCELA,
    DESEJA_INFORMAR_DATA,
    FINALIZAR_LANCAMENTO,
    INFORMAR_DATA,
    INFORMAR_VALOR,
    INFORMAR_DESCRICAO,
    INFORMAR_PARCELA,
    DESEJA_INFORMAR_CARTAO,

    LANCAMENTO_RAPIDO
}
